#lang pollen

◊(define-meta title "20% Project - ProjectEuler #40, 44, and 47")
◊(define-meta published "2015-04-15")
◊(define-meta topics "Teaching Credential,20% Project,Project Euler")

◊(require scribble-math)
◊(use-mathjax)
◊(define ($ . xs) 
  `(mathjax ,(apply string-append `("$" ,@xs "$"))))
◊(define ($$ . xs)
  `(mathjax ,(apply string-append `("$$" ,@xs "$$"))))

◊figure["ProjectEuler29a.png"]

◊link["https://projecteuler.net/problem=29"]{Project Euler}

Like the last problem I find it's informative to start out with an inelegant solution and try to find an elegant one at the end.

We start by generating an array of the form ◊${a^b} from ◊b{a} = ◊${2} to ◊${100} and ◊b{b} = ◊${2} to ◊${100}.

◊figure["ProjectEuler29b.png"]
◊b{Problem 47}

The first two consective numbers to have two distince prime factors are:

◊${14=2×7}
◊${15=3×5}

The first three consective numbers to have three distinct prime factors are:

◊${644=2^2×7×23}
◊${644=2^2×7×23}
◊${644=2^2×7×23}

Find the first four consective numbers to have four distinct prime factors. What is the first of these numbers?

◊blockcode[#:filename "Mathematica"]{
prob47 = Flatten[Table[Length[FactorInteger[n]], {n, 1, 200000}]];
prob47b = Table[Sum[prob47[[a + i]], {i,0,3}], {a, 1, 199997}];
Position[prob47b, 16]
}

=====================

◊b{Problem 44}

Pentagonal numbers are generated by the formula, ◊${P_n=n(3n-1)/2}. The first ten pentagonal numbers are:

◊${1, 5, 12, 22, 35, 51, 70, 92, 117, 145,} ...

It can be seen that ◊${P_4 + P_7 = 22 + 70 = 92 = P_8}. However, their difference, 70 - 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, ◊${P_j} and ◊${P_k}, for which their sum and difference are pentagonal and ◊${D = |P_k - P_j|} is minimised; what is the value of D?

◊blockcode[#:filename "Mathematica"]{
prob44a = Table[m×(m + 1)/2, {m, 1, 100000}];
prob44b = Table[n×(3×n-1)/2, {n, 1, 100000}];
prob44c = Table[o×(2×o-1), {o, 1, 100000}];
Intersection[prob44a, prob44b, prob44c]
}


=====================

◊b{Problem 40}

An irrational decimal fraction is created by concatenating the positive integers:

◊${\large{0.123456789101}\huge{1}\large{12131415161718192021...}}

It can be seen that the ◊${12^{th}} digit of the fractional part is 1.

If ◊${d_n} represents the n◊sup{th} digit of the fractional part, find the value of the following expression.

◊${d_1 × d_{10} × d_{100} × d_{1000} × d_{10000} × d_{100000} × d_{1000000}}

◊blockcode[#:filename "Mathematica"]{
prob40 = Flatten[IntegerDigits[Table[n, {n, 1, 200000}]]];
Product[prob40[[10^a]], {a, 0, 6}]
}
